---
# This playbook install the apps required in a server

#- name: add splunk group
  #tags:
   #- install
   #- security
  #group: name=splunk state=present
- name: Remove the user "splunk'
  user:
    name: splunk
    state: absent
    remove: yes

- name: add splunk user
  tags:
   - install
  # - security
  shell: adduser splunk
 # user: name=splunk comment="Splunk service user" shell=/usr/sbin/useradd groups=splunk createhome=no

- name: make /opt writetable by splunk
  tags:
   - install
  file: path=/opt mode=777

- name: checking if splunk is install
  tags: install
  stat: path=/opt/splunk
  register: splunk_path

- name: is splunk installed?
  tags: install
  debug: msg='splunk is already installed under /opt/splunk'
  when: splunk_path.stat.exists

- name: download {{splunk_binary}}
  tags:
   - install
  get_url: url={{wget_url}} dest=/tmp/{{splunk_binary}} mode=777
  when: splunk_path.stat.exists == false


- name: install splunk binary
  tags:
   - install
  unarchive: src=/tmp/{{splunk_binary}} dest=/opt/ owner=splunk group=splunk creates=yes remote_src=yes
  become: yes
  become_user: splunk
  when: splunk_path.stat.exists == false

- name: accept license and start splunk
  tags:
   - install
  shell: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd splunkteja
  become: yes
  become_user: splunk
  when: splunk_path.stat.exists == false

- name: enable boot-start
  tags:
   - install
  shell: /opt/splunk/bin/splunk enable boot-start
  when: splunk_path.stat.exists == false
#  become: yes
#  become_user: splunk

- name: make /etc/init.d/splunk executable
  tags:
   - install
  file: path=/etc/init.d/splunk mode=755
